version: '3'
services:
  web:
    build: .
    command: foreman start
    ports:
      - "5000:5000"
    # volumes:
      # - .:/opt/sinatra-sidekiq-example #Originally this was the just a shared volume for the actual server files
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis

networks:
  default:
  #   external:
  #     name: ${NETWORK:-webproxy}
  # outside:
    external:
      name: ${SERVICE_NETWORK:-webservices}