web:
  build: .
  command: foreman start
  ports:
    - "5000:5000"
  # volumes:
    # - .:/opt/sinatra-sidekiq-example #Originally this was the just a shared volume for the actual server files
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
redis:
  image: redis